### ISSUE TITLE
어피니티 퍼블리셔 프로그램에서 export된 PDF에서 해당 서체 문제 발생

### ISSUE THREAD

**Issue by BK-0502** [wanteddev/wanted-sans#19]
어피니티 퍼블리셔 프로그램에서 Wanted Sans 및 Pretendard 글꼴 사용 시, export된 PDF상에서 해당 글꼴의 크기가 변경되고 겹쳐서 나오는 현상이 발생합니다. (첨부파일 참조)
[ecported pdf.pdf](https://github.com/user-attachments/files/16171612/ecported.pdf.pdf)

어피니티 포럼에서 [논의](https://forum.affinity.serif.com/index.php?/topic/207647-problems-with-characters-when-exporting-to-pdf/#comment-1243301)해 본 결과, kenmcd 님께서 아래와 같은 부분을 짚어 주셨기에 여기 남깁니다. 

Something is not right in these fonts.
I think it is the .null character, which should be U+0000, but the code is blank.
FontLab does not like it and changes it to CID1.
FontCreator opens it as-is (but FC always fixes stuff it does not like).
OTMaster shows an error on the .notdef (which tells me it does not like the file format), and it shows the .null as CID1 like FL.
This makes me think there is an issue with reading the cmap table.
This character map table issue would affect the sub-setting.

So I deleted the .null character and re-exported the OTF font from FC.
That caused the cmap table to be rebuilt.
And this font works as expected.

**Comment by orioncactus** [comment]
안녕하세요! Pretendard와 Wanted Sans를 아껴주시고, 두 폰트에서 발생하는 문제점을 알려주셔서 감사합니다 :)

우선 포럼에서 kenmcd님께서 알려주신 것처럼, space 글리프 부분에 유니코드를 `u0000`부터 `u001f`까지 포함시켜보았으나 문제가 동일하게 발생하는 것을 확인했으며, 이어서 Pretendard Std 및 Pretendard JP에서도 동일하게 발생하며, Wanted Sans Std에서는 발생하지 않는 것을 보았을 때, 폰트가 CID-Keyed 방식이고, 특정 조건이 더해져 문제가 발생하는 것으로 짐작해보았습니다.
다음으로 실험해본 것은, CID-Keyed인 폰트에서 UPM(Path를 그리는 아트보드 크기 개념)이 1000이 아닐 때 발생하는 것으로 짐작하고, UPM이 2048인 Wanted Sans에서 UPM을 1000으로 설정한 것인데요, 내보냈더니 정상적으로 표시되는 것을 확인했습니다. 따라서 Affinity Publisher에서 발생하는 문제는 폰트가 다음과 같은 조건을 모두 만족할 때 발생합니다.
1. 폰트가 CID-Keyed 기반이다.
2. 폰트의 UPM이 1000이 아니다.

해결 방법으로는 CID-Keyed 기반인 OTF 확장자에서 UPM을 1000으로 맞추는 것과, CID-Keyed 기반이 아닌 TTF 확장자로 Pretendard 또는 Wanted Sans를 쓰는 것인데요, UPM을 1000으로 맞추는 것에 대해서는 여러 폰트 포럼에서 이제는 지키지 않아도 되는 점으로([Glyphs 포럼 참조](https://forum.glyphsapp.com/t/upm-value-for-otf-fonts/1858/6)) 이야기하고 있기 때문에, Affinity Publisher에서 이 문제를 해결할 수 있도록 자세한 조건을 알려드려볼 수 있을 듯합니다.

이어서 제보를 해보려고 하는데요, 멀지 않은 시기에 제가 이어서 알려주신 스레드에 적어보겠습니다.

따라서 문제가 해결되기 전까지는 TTF 확장자로 대신 쓰시는 것을 추천드립니다.

**Comment by orioncactus** [comment]
@BK-0502 안녕하세요! 방금 포럼에 댓글을 달아두었습니다.

이어서 이 이슈는 Closed 처리해두려고 합니다. 추가적으로 도움이 필요하시다면 언제든지 알려주세요! ✨
